name: gnn
channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - exceptiongroup=1.2.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.2
  - pillow=10.3.0
  - pip=23.3.1
  - pluggy=1.0.0
  - pybind11-abi=4
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.10.14
  - pytorch=2.3.0
  - pytorch-cluster=1.6.3
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.2
  - pytorch-sparse=0.6.18
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - scipy=1.13.0
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - tomli=2.0.1
  - torchtriton=2.3.0
  - torchvision=0.18.0
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - biopython==1.83
      - click==8.1.7
      - contextlib2==21.6.0
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - flash-attn==2.3.2
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - joblib==1.4.0
      - ml-collections==0.1.1
      - mmcif==0.88.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - ninja==1.11.1.1
      - ordered-set==4.1.0
      - orjson==3.10.3
      - pandas==2.2.2
      - protobuf==4.25.3
      - psutil==5.9.8
      - pulp==2.8.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - rdkit-pypi==2022.9.5
      - rnapolis==0.3.11
      - scikit-learn==1.4.2
      - sentry-sdk==2.0.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - soupsieve==2.5
      - threadpoolctl==3.5.0
      - torch-geometric==2.5.3
      - tqdm==4.66.2
      - tzdata==2024.1
      - viennarna==2.6.4
      - wandb==0.16.6
      - yarl==1.9.4
